---
namespace: batodt
name: oneagent
version: 1.2.5
readme: README.md
authors:
  - batodt
description: Module to install and configure Dynatrace OneAgent deployment (personal dev version)
license_file: LICENSE
tags:
  - dynatrace
  - oneagent
  - agent
  - deployment
  - monitoring
  - infrastructure
  - linux
  - windows
repository: https://github.com/batodt/Dynatrace-OneAgent-Ansible
documentation: https://docs.dynatrace.com/docs/setup-and-configuration/dynatrace-oneagent/deployment-orchestration/ansible
build_ignore:
  - .*
  - CHANGELOG.md
  - git-conventional-commits.yaml
  - pyproject.toml
  - venv
